kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # name: maprfs-pvc-prometheus
  name: pvc-prometheus
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: maprfs-sc-tmp
  resources:
    requests:
      storage: 300M
