apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: ivan123
        - name: POSTGRES_USER
          value: ivan
        image: postgres
        name: db
        ports:
        - containerPort: 5432
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    name: db
  spec:
    ports:
    - port: 5432
      targetPort: 5432
    selector:
      name: db
  
