apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: fetcher
  name: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fetcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fetcher
    spec:
      restartPolicy: Always
      containers:
        - image: diptan/fetcher:latest
          name: fetcher
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: fetcher
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    name: fetcher