apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: diptan/mongo
        name: mongo
        ports:
        - containerPort: 27017
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongo
  spec:
    ports:
    - port: 27017
      targetPort: 27017
    selector:
      name: mongo
  