apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: processor
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: processor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: processor
    spec:
      restartPolicy: Always
      containers:
        - name: processor
          image: diptan/processor:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
#          ports:
#            - containerPort: 8081
#---
#  apiVersion: v1
#  kind: Service
#  metadata:
#    name: processor
#  spec:
#    ports:
#    - port: 8081
#      targetPort: 8081
#    selector:
#      name: processor
